### ISSUE TITLE
TicketForward did not work with this module

### ISSUE THREAD

**Issue by AlexeyAG** [znuny/Znuny4OTRS-SecondTicketCreateScreen#3]
Hi!

On OTRS v3.3 instalation of Znuny4OTRS-SecondTicketCreateScreen lead to 
problem with AgentTicketForward dialog. 

Steps
1) Install Znuny4OTRS-SecondTicketCreateScreen
2) open AgenTicketZoom dialog of any ticket
3) Press Forward on first client article
4) Enter any client name into "To" field
        in my case client address was copied to all three fields (To Cc HiddenCopy) and 
        form didnot submit after that.

Can you fix that issue ?

**Comment by thorsteneckel** [comment]
Hi @AlexeyAG, we will look into this. Thanks for reporting the issue.

**Comment by dennybresch** [comment]
Hi @AlexeyAG, 
we fixed the bug in version 1.1.3.

Denny Bresch,
Thank you.
