### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sirrus** [znuny/Znuny4OTRS-SecondTicketCreateScreen#4]
Hi,

it would be great if you could add settings for:
* TimeUnits
* Queue
* Page Title (h1)

**Comment by dennybresch** [comment]
Hi @sirrus,

we are so sorry, but it is not possible to add this configuration for these two masks in this AddOn.

We are using framework modules AgentTicketEmail and AgentTicketPhone as backend and we can only use the configuration of Frontend::Agent::Ticket::ViewEmailNew  and Frontend::Agent::Ticket::ViewPhoneNew.

This package is for free and can be used by everyone.
If you want or need additional adjustments, we would need a support contract with you.

Please take a look at http://znuny.com/en/#!/support

Best regards
Denny

**Comment by sirrus** [comment]
OK thanks for looking into it - we'll solve it with Ticket Templates Addon.
