### ISSUE TITLE
Link to latest version links to an old version

### ISSUE THREAD

**Issue by tipue-dev** [znuny/Znuny4OTRS-SecondTicketCreateScreen#5]
### Environment

- Browser:      
- Framework version: 

### Expected behavior
The link ``Download the [latest version](https://addons.znuny.com/api/addon_repos/public/2106/latest).`` should start the download of version 6.**3**.1 (or even better would be a 6.**4**.1 ;) ).

### Actual behavior
Starts download of version 6.**2**.1

### How to reproduce

1. Go to 'https://github.com/znuny/Znuny4OTRS-SecondTicketCreateScreen'
2. Click on 'latest version'
3. Look at the filename

### Additional information
I was talking about the dev branch, but i can see, that there is a rel-6.4 branch with the same problem.
The rel-6.4 branch has the additional problem, that the version number has not been raised to 6.**4**.1 but is still at 6.**3**.1

**Comment by rkaldung** [comment]
@tipue-dev Thank you for reporting, I fixed the outdated links with 763c97b2664b1fe209c505d515cbc2f01f2feebb
